### ISSUE TITLE
Dump Progress Bar Tracker>App

### ISSUE THREAD

**Issue by jiska2342** [seemoo-lab/fitness-app#10]
Before a dump is transmitted from the app to the tracker (firmware, server dump response), the c0-message has a length indicator. Use this to display a progress bar.

c0 24 [1 byte dumptype] [4 bytes length] [2 bytes crc] 10
      

In the other direction, tracker to app, there is no length indicator. Show the number of transmitted BLE frames or spinning bar to indicate something is still happening.

**Comment by anykeyjunkie** [comment]
This ticket is only for the direction Tracker > App

**Comment by stekreis** [comment]
solved for tracker > app

app > tracker has its own issue #17, but will be dismissed anyway
