### ISSUE TITLE
Progress Bar for transmitting data to tracker

### ISSUE THREAD

**Issue by anykeyjunkie** [seemoo-lab/fitness-app#17]
Show a progress bar if data is transmitted from the app to the tracker. See #10 for details.

**Comment by stekreis** [comment]
The original idea of showing the progress of transmitting data **from the app to the tracker** can be split in two parts:
1) Transmission of FW (solved with #32 )
2) Transmission of Megadump/Microdump (did not work anyway, option will be removed with #47 )

So as soon as #47 is solved, this issue can be closed as well.
