### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by AmorphDesign** [seemoo-lab/fitness-app#22]

**Comment by AmorphDesign** [comment]
![icon mit weiss](https://user-images.githubusercontent.com/40056100/41224713-68b2ac32-6d6d-11e8-9bfd-8f885243baa3.png)
![icon tran](https://user-images.githubusercontent.com/40056100/41224714-68d4931a-6d6d-11e8-9ea0-8b8a8bcc1a1a.png)

**Comment by AmorphDesign** [comment]
Icon mit weißem Hintergrund

![icon mit weiss](https://user-images.githubusercontent.com/40056100/41224733-78d93eb4-6d6d-11e8-9354-6e95b6d6dc15.png)

**Comment by AmorphDesign** [comment]
Icon transparent

![icon tran](https://user-images.githubusercontent.com/40056100/41224755-875e073a-6d6d-11e8-903a-813c4d4216bc.png)

**Comment by anykeyjunkie** [comment]
this ticket is about adopting the icon as app icon and using it in the sliding menu as a header
