### ISSUE TITLE
Save Encryption Key automatically

### ISSUE THREAD

**Issue by stekreis** [seemoo-lab/fitness-app#24]
Currently, when receiving the encryption key from the Tracker, one has to save it manually, then copy it again via a file manager and paste it to the device settings.

Automate this process or at least allow the key to be copied inside the app.

[remark] If I remember correctly, the automation worked in an earlier version.

**Comment by anykeyjunkie** [comment]
It would be sufficient to enable copy-paste for the listview as well

**Comment by Tobis93** [comment]
@anykeyjunkie Did you already work on this? I think I have a solution for it if you didn't.
