### ISSUE TITLE
Parse github dir and download FW

### ISSUE THREAD

**Issue by stekreis** [seemoo-lab/fitness-app#35]
Parse FW directory on https://github.com/seemoo-lab/fitness-firmware/tree/master/firmwares and download FW files for flashing

maybe combine with #31

**Comment by anykeyjunkie** [comment]
If not possible within time, fallback solution would be to package modified firmwares into the app bundle and offer them as a selection to the user.

**Comment by anykeyjunkie** [comment]
built with #70
