### ISSUE TITLE
Charge 2 not supported?

### ISSUE THREAD

**Issue by huguesb** [seemoo-lab/fitness-app#4]
After setting up my Fitbit Charge 2 with the official app and updating the firmware on it, the open fitbit app is able to detect it but reports "authentication credentials unavailable" and "encryption key unavailable". Is this a known issue or did I miss a step somewhere?

**Comment by jiska2342** [comment]
Sorry for the late answer.
You need to log in with your Fitbit account to get authentication credentials from the server (via online->authenticate). If you can get the encryption key or not depends on your firmware version. To the best of our knowledge, receiving authentication credentials this way and using live mode should work on all trackers, we even tested it on the Ionic smartwatch. We're currently working on getting a more intuitive user interface and a comprehensive feature list for all models and firmware versions.
