### ISSUE TITLE
Use with Surge

### ISSUE THREAD

**Issue by jugendhacker** [seemoo-lab/fitness-app#49]
Can I use this App with my Fitbit Surge?

**Comment by jiska2342** [comment]
Hi :)
We don't have a Fitbit Surge, so we never tested that one. Most likely, live mode will work - would be interesting for us if you could try this. Flashing custom firmware is currently supported for Fitbit Flex only.

**Comment by jugendhacker** [comment]
Hi
The livemode is working with my surge...

**Comment by jiska2342** [comment]
Thank you for testing :) I owe you a bottle of mate at MRMCD or 35C3 ;)
