### ISSUE TITLE
Authentication Credentials

### ISSUE THREAD

**Issue by jiska2342** [seemoo-lab/fitness-app#76]
Login is correct according to greeting, but the user credentials are not copied into the app.

**Comment by jiska2342** [comment]
...on the first try not displayed, needs some forward/backward clicking. Usability only.

**Comment by jiska2342** [comment]
was related to a clearCache() action that removed the serialNumber and then resulted in an invalid BLECredentials request to the server.

**Comment by jentzd** [comment]
Hello, having a similar issue as reported here.
After copying the long string back into the app, it appears to authenticate OK ( bottom of screen says Hello David Jentz!)
However, back in the app, not able to proceed. Each time I click around another long string from the fitbit server is displayed.

**Comment by jiska2342** [comment]
@jentzd sorry for not replying so long. Did you use the prebuilt version in `/release` or build the project on your own? The prebuilt release is older than the commit where I fixed this bug.

I will have some time next week and can check out the issue with my trackers, try if the app is still working with the Fitbit servers and compile a new prebuilt release.

**Comment by jentzd** [comment]
Ah, yes. Used the prebuilt version in /release.

Can try building the project on my own ( but do not have a build
environment stood up yet). The /release was a nice option, could download
directly to phone.

**Comment by jiska2342** [comment]
Hi @jentzd , I build a new version and pushed it into `/release`. Authentication with a Fitbit Ionic worked but was a but buggy for me. I was able to solve this issue by switching between the *Information* and *Live Mode* screens, but had to copy the authentication string twice.

**Comment by jentzd** [comment]
Thank you. I have tried the new compiled software and it is now getting
passed the step of authenticating with the Fitbit severs.

Unfortunately it is erroring on the next step now. Something to do with
applying firmware?

**Comment by jiska2342** [comment]
@jentzd what is the next step? Can you send a screenshot or the error message you get?
