### ISSUE TITLE
Not able to Scan Fitbit Charge HR.

### ISSUE THREAD

**Issue by RajatSharma11** [seemoo-lab/fitness-app#77]
@jiska2342  I tried scanning my Fitbit Charge HR (Firmware version: 18.128), but it is not able to scan it. Please help!

**Comment by jiska2342** [comment]
Which version did you use? The compiled apk or did you build it on your own?

Moreover, a Fitbit will only appear in scanning, if it is currently not paired. If you still have the official Fitbit app open in background, scanning will most likely not work. Ideally, close the official Fitbit app and restart Bluetooth on your smartphone.

**Comment by RajatSharma11** [comment]
Thanks, @jiska2342 I build the apk on my own. I am able to connect it now, but i need to try scanning it many times. Can you tell me why is it not able to scan in first or second attempt?

**Comment by jiska2342** [comment]
Scanning is pretty slow, also in the official Fitbit app. It is hard to notice there, as it always shows your default tracker and connects in background - only during pairing finding your tracker takes ages. In general, Bluetooth scanning takes some time. There is currently one bug in our app that forces a reconnect after finding the tracker, but I guess except from that, the only way to improve user experience would be not to focus on the connection but always cache tracker information and connect in background.

**Comment by RajatSharma11** [comment]
Thanks, @jiska2342 for all the help.
