### ISSUE TITLE
Remember & connect to last device

### ISSUE THREAD

**Issue by anykeyjunkie** [seemoo-lab/fitness-app#8]
The app should remember which was the last device and should automatically try to connect to this one when the app is started. This means that after successful device connection, the typical information page is shown.

Furthermore, we would like to have an additional button on the three dots menu "Switch device" which opens the very first site of the app where a user can pair new devices or can connect to a different one.

**Comment by Tobis93** [comment]
Seems to be broken after some of the recent changes

**Comment by Tobis93** [comment]
Fixed
